# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2
# This configuration is based upon: https://github.com/RobCannon/boxstarter/blob/32fef6dbc8b588df1b740d952c7b34ba9238d4e2/configuration.dsc.yaml
properties:
  configurationVersion: 0.2.0

  resources:
    - resource: DeveloperMode
      directives:
        description: Enable Developer Mode
        module: Microsoft.Windows.Developer
        allowPrerelease: true
      settings:
        Ensure: Present

    # IME
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Google Japanese Input
        allowPrerelease: true
      settings:
        id: Google.JapaneseIME
        source: winget

    # Fonts
    - resource: DSCR_Font/cFont
      directives:
        description: Install SauceCodePro Font
      settings:
        FontName: SauceCodePro NF Regular
        FontFile: https://github.com/ryanoasis/nerd-fonts/raw/2.1.0/patched-fonts/SourceCodePro/Regular/complete/Sauce%20Code%20Pro%20Nerd%20Font%20Complete%20Mono%20Windows%20Compatible.ttf

    - resource: DSCR_Font/cFont
      directives:
        description: Install Source Han Code JP Font
      settings:
        FontName: Source Han Code JP
        FontFile: https://github.com/adobe-fonts/source-han-code-jp/releases/download/2.012R/SourceHanCodeJP.ttc

    - resource: DSCR_Font/cFont
      directives:
        description: Install CaskaydiaCove Font
      settings:
        FontName: CaskaydiaCove NF Regular
        FontFile: https://github.com/ryanoasis/nerd-fonts/raw/2.1.0/patched-fonts/CascadiaCode/complete/Caskaydia%20Cove%20Nerd%20Font%20Complete%20Mono%20Windows%20Compatible.ttf

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install PowerShell 7
        allowPrerelease: true
      settings:
        id: Microsoft.PowerShell
        source: winget

    # Web browser
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Google Chrome
        allowPrerelease: true
      settings:
        id: Google.Chrome
        source: winget

    # WSL
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Ubuntu 22.04 LTS (WSL)
        allowPrerelease: true
      settings:
        id: Canonical.Ubuntu.2204
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Windows Terminal Preview
        allowPrerelease: true
      settings:
        id: Microsoft.WindowsTerminal.Preview
        source: winget

    # SCM
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Git
        allowPrerelease: true
      settings:
        id: Git.Git
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install GitHub CLI
        allowPrerelease: true
      settings:
        id: GitHub.cli
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install GitHub Desktop
        allowPrerelease: true
      settings:
        id: GitHub.GitHubDesktop
        source: winget

    # Dev tools
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Visual Studio Code
        allowPrerelease: true
      settings:
        id: Microsoft.VisualStudioCode
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Docker Desktop
        allowPrerelease: true
      settings:
        id: Docker.DockerDesktop
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install AWS CLI
        allowPrerelease: true
      settings:
        id: Amazon.AWSCLI
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Glow - Render markdown on the CLI, with pizzazz!
        allowPrerelease: true
      settings:
        id: charmbracelet.glow
        source: winget

    # Programming Languages
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Go Programming Language
        allowPrerelease: true
      settings:
        id: GoLang.Go
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Node.js LTS
        allowPrerelease: true
      settings:
        id: OpenJS.NodeJS.LTS
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Python Programming Language
        allowPrerelease: true
      settings:
        id: Python.Python.3.11
        source: winget

    # Microsoft Apps
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Microsoft Office
        allowPrerelease: true
      settings:
        id: Microsoft.Office
        source: winget

    # - resource: Microsoft.WinGet.DSC/WinGetPackage
    #   directives:
    #     description: Install Microsoft Teams
    #     allowPrerelease: true
    #   settings:
    #     id: Microsoft.Teams
    #     source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install PowerToys
        allowPrerelease: true
      settings:
        id: Microsoft.PowerToys
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install OneDrive
        allowPrerelease: true
      settings:
        id: Microsoft.OneDrive
        source: winget

    # Cloud Storages
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Evernote
        allowPrerelease: true
      settings:
        id: evernote.evernote
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Google Drive
        allowPrerelease: true
      settings:
        id: Google.GoogleDrive
        source: winget

    # Communication
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Discord
        allowPrerelease: true
      settings:
        id: Discord.Discord
        source: winget
        
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install LINE
        allowPrerelease: true
      settings:
        id: LINE.LINE
        source: winget

    # Miscs
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Ditto
        allowPrerelease: true
      settings:
        id: Ditto.Ditto
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install 7-Zip ZS
        allowPrerelease: true
      settings:
        id: mcmilk.7zip-zstd
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Lightshot
        allowPrerelease: true
      settings:
        id: Skillbrains.Lightshot
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Krita
        allowPrerelease: true
      settings:
        id: KDE.Krita
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Wondershare Filmora
        allowPrerelease: true
      settings:
        id: Wondershare.Filmora
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Adobe Acrobat Reader DC (64-bit)
        allowPrerelease: true
      settings:
        id: Adobe.Acrobat.Reader.64-bit
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: OBS Studio
        allowPrerelease: true
      settings:
        id: OBSProject.OBSStudio
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install QuickLook
        allowPrerelease: true
      settings:
        id: QL-Win.QuickLook
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Parsec
        allowPrerelease: true
      settings:
        id: Parsec.Parsec
        source: winget

    # Registry Setting
    - resource: PSDscResources/Registry
      directives:
        description: Show Hidden Files
      settings:
        Key: HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced
        ValueName: Hidden
        ValueType: DWord
        ValueData: 1

    - resource: PSDscResources/Registry
      directives:
        description: Do not Hide File Extensions
      settings:
        Key: HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced
        ValueName: HideFileExt
        ValueType: DWord
        ValueData: 0

    - resource: PSDscResources/Registry
      directives:
        description: Navigation Pane Expand to Current Folder
      settings:
        Key: HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced
        ValueName: NavPaneExpandToCurrentFolder
        ValueType: DWord
        ValueData: 1

    - resource: PSDscResources/Registry
      directives:
        description: Turn off Search box on Taskbar
      settings:
        Key: HKCU:\Software\Microsoft\Windows\CurrentVersion\Search
        ValueName: SearchboxTaskbarMode
        ValueType: DWord
        ValueData: 0
